"""Drop balances table

Revision ID: 931d1952f3e7
Revises: 20260622_0002
Create Date: 2026-06-23 13:00:08.589500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931d1952f3e7'
down_revision: Union[str, Sequence[str], None] = '20260622_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balances_id'), table_name='balances')
    op.drop_table('balances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.CheckConstraint('amount >= 0::double precision', name=op.f('ck_balances_amount_non_negative')),
    sa.CheckConstraint('from_user_id <> to_user_id', name=op.f('ck_balances_distinct_users')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('balances_from_user_id_fkey')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('balances_group_id_fkey')),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('balances_to_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('balances_pkey')),
    sa.UniqueConstraint('group_id', 'from_user_id', 'to_user_id', name=op.f('uq_balances_group_from_to'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_balances_id'), 'balances', ['id'], unique=False)
    # ### end Alembic commands ###
