"""Change Float to Integer for Currency

Revision ID: a8ec4f3aca3c
Revises: 931d1952f3e7
Create Date: 2026-06-23 13:12:43.376800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.models


# revision identifiers, used by Alembic.
revision: str = 'a8ec4f3aca3c'
down_revision: Union[str, Sequence[str], None] = '931d1952f3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_participants', schema=None) as batch_op:
        batch_op.alter_column('amount_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=backend.models.Currency(),
               existing_nullable=True)
        batch_op.alter_column('amount_owed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=backend.models.Currency(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_expense_participants_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=backend.models.Currency(),
               existing_nullable=True)

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=backend.models.Currency(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_settlements_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_payee_id'), ['payee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_payer_id'), ['payer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_payer_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_payee_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_group_id'))
        batch_op.alter_column('amount',
               existing_type=backend.models.Currency(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=backend.models.Currency(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('expense_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_participants_user_id'))
        batch_op.alter_column('amount_owed',
               existing_type=backend.models.Currency(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('amount_paid',
               existing_type=backend.models.Currency(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
